### ISSUE TITLE
SVG gradient fallback not rendered properly

### ISSUE THREAD

**Issue by joushx** [paulkinzett/toolbar#10]
When using the vertical toolbar in a browser, that supports only the SVG fallback, the background is not rendered properly as the gradient is the same height as with the horizontal toolbar.

![toolbar-vertical](https://f.cloud.github.com/assets/832178/143669/d7834e28-73bd-11e2-9ea9-998e4d245fb6.png)

Needs something like this:

``` css
.tool-right .tool-item, .tool-left .tool-item {
  background: url("data:image/svg+xml;base64,PD94[...]jwvc3ZnPg==") repeat scroll 0 0 transparent;
}
```
