### ISSUE TITLE
jquery.toolbar with Bootstrap 3.0.3 isn't display correctly.

### ISSUE THREAD

**Issue by ghernandezr** [paulkinzett/toolbar#43]
When I use jquery.toolbar with bootstrap 3.0.3, the button and menu isn't display correctly. 
<br/>
![jquery toolbar with bootstrap 3 0 3](https://cloud.githubusercontent.com/assets/12530702/7995739/02de312e-0ae7-11e5-82d6-edf5b80f5f10.png)

**Comment by ghernandezr** [comment]
I find a solution doing my own jquery.toolbar.bootstrap3.css and puting this styles:
<pre>
<code>
.btn-toolbar{
	width: 35px;
 	height: 35px;
	line-height: 2px;
}

.tool-item{
	  width: 35px;
	  height: 100%;
}
</code></pre>
maybe you can find better solution.

**Comment by ihmcjacky** [comment]
@ghernandezr Thx for the hotfix, it works perfectly, hope for integrating to master branch

**Comment by hoigo** [comment]
This worked for me (inside my css file):

* {
	-webkit-box-sizing: content-box;
}

**Comment by smeinecke** [comment]
It seems as bootstrap overwrite default value of box-sizing for all elements by following CSS rule:
```css
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

So, you probably have to add:
```css
.tool-container, .tool-item, .btn-toolbar {
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
}
```
